spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/test_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:123four}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false